image: python2.7
env:
    - GOPATH=/var/cache/drone
script:
    - make bootstrap
    - make test
services:
    - redis
    - postgres
    - dockerfile/nginx
deploy:
    bash:
        script:
          - make deploy
notify:
    email:
        recipients:
            - gotsyk@gmail.com
